<div class="col-lg-12">
    <section class="panel">
        <header class="panel-heading">
            Adiantamento de disciplina
        </header>
        <div class="panel-body">
            <form class="form-horizontal" role="form" name="adiantamentoForm" id="solicitacaoForm" method="post" enctype="multipart/form-data" action="<?php echo $this->url('solicitacao/adiantamento-disciplina'); ?>">
                <div class="form-group col-lg-14 text-center">
                    <?php echo $this->flashMessenger()->render('error', array('alert alert-block alert-danger')); ?>
                    <?php echo $this->flashMessenger()->render('info', array('alert alert-info')); ?>
                    <?php echo $this->flashMessenger()->render('success', array('alert alert-success')); ?>
                </div>
                <div class="form-group">
                    <label  class="col-lg-2 col-sm-2 control-label">Nome</label>
                    <div class="col-lg-10">
                        <input type="text" name="nomeUsuario" class="form-control" value="<?php echo $this->nomeUsuario; ?>" disabled>
                        <input type="hidden" name="idUsuario" value="<?php echo $this->idUsuario; ?>">
                    </div>
                </div>
                <div class="form-group">
                    <label  class="col-lg-2 col-sm-2 control-label">Matrícula</label>
                    <div class="col-lg-10">
                        <input type="text" name="matriculaUsuario" class="form-control" value="<?php echo $this->matricula; ?>" disabled>
                    </div>
                </div>
                <?php if(!is_null($this->curso)) : ?>
                <div class="form-group">
                    <label  class="col-lg-2 col-sm-2 control-label">Curso</label>
                    <div class="col-lg-10">
                        <input type="text" name="descricaoCurso" class="form-control" value="<?php echo $this->curso['descricao']; ?>" disabled>
                        <input type="hidden" name="idCurso" value="<?php echo $this->curso['id']; ?>">
                    </div>
                </div>
                <?php endif; ?>
                <div class="form-group">
                    <label  class="col-lg-2 col-sm-2 control-label">Disciplina</label>
                    <div class="col-lg-10">
                        <select class="form-control disciplina" name="disciplina1" required>
                            <option value="">Selecione a disciplina</option>
                            <?php foreach($this->disciplinas as $disciplina) : ?>
                            <option value="<?php echo $disciplina->getId(); ?>"><?php echo $disciplina->getCod() . ' - ' . $disciplina->getDescricao(); ?></option>
                            <?php endforeach; ?>
                        </select>
                        <input type="hidden" name="totalDisciplinas" id="totalDisciplinas" value="1">
                    </div>
                </div>
                <div class="end-disc-select">
                    <!-- FIM DO SELECT DE DISCIPLINAS -->
                </div>
                <div class="form-group">
                    <label class="col-lg-2 col-sm-2 control-label">Anexo</label>
                    <div class="col-lg-10">
                        <input type="file" id="arquivo" name="arquivo">
                        <p class="help-block">Serão aceitos arquivos de extensão <i>.doc, .jpg e .pdf</i> de tamanho até 10mb.</p>
                    </div>
                </div>
                <div class="form-group submit">
                    <div class="col-lg-offset-2 col-lg-10">
                        <button type="submit" class="btn btn-info">Enviar</button>
                        <button class="btn btn-warning" type="button" onclick="insereDisciplina()">Adicionar disciplina</button>
                        <button class="btn btn-danger" type="button" onclick="excluirDisciplina()">Excluir disciplina</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
</div>