<div class="col-lg-12">
    <section class="panel">
        <header class="panel-heading">
            Minhas solicitações
        </header>
        <div class="panel-body table-responsive">
            <?php if (!$this->solicitacoes->count()) : ?>
                Você ainda não fez nenhuma solicitação. Selecione a opção <i>"Nova Solicitação"</i> no menu ao lado.
            <?php else : ?>
                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th>Matrícula</th>
                            <th>Protocolo</th>
                            <th>Tipo de Solicitação</th>
                            <th>Data de abertura</th>
                            <th>Status</th>
                        </tr>
                        <?php foreach ($this->solicitacoes as $solicitacao) : ?>
                            <tr onclick="visualizarSolicitacao('<?php echo $solicitacao['protocolo']; ?>')">
                                <td><?php echo $solicitacao['matricula']; ?></td>
                                <td><?php echo $solicitacao['protocolo']; ?></td>
                                <td><?php echo $solicitacao['tipo']; ?></td>
                                <td><?php echo $solicitacao['data_exibir']; ?></td>
                                <td>
                                    <?php
                                    switch ((int) $solicitacao['fk_status']) {
                                        case 1:
                                            echo " <span class='label label-primary'> Aberto </span> ";
                                            break;
                                        case 2:
                                            echo " <span class='label label-warning'> Em atendimento </span> ";
                                            break;
                                        case 3:
                                            echo " <span class='label label-warning'> Encaminhado </span> ";
                                            break;
                                        case 4:
                                            echo " <span class='label label-success'> Encerrado </span> ";
                                            break;
                                        case 5:
                                            echo " <span class='label label-danger'> Cancelado </span> ";
                                            break;
                                    }
                                    ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>
        </div>
    </section>
</div>