<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Secretaria Online</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <link href="css/ionicons.min.css" rel="stylesheet" type="text/css" />
        <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
        <link href="css/style.css" rel="stylesheet" type="text/css" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <script src="js/jquery.min.js" type="text/javascript"></script>
        <script src="js/bootstrap.min.js" type="text/javascript"></script>
        <script src="js/Director/app.js" type="text/javascript"></script>
    </head>
    <body class="skin-black">
        <header class="header">
            <a href="#" class="logo">Secretaria Online</a>
            <nav class="navbar navbar-static-top" role="navigation">
                <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-right">
                    <ul class="nav navbar-nav">
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-user"></i>
                                <span>Evandro Silva <i class="caret"></i></span>
                            </a>
                            <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
                                <li class="dropdown-header text-center">TADS - NOITE</li>
                                <li>
                                    <a href="#"><i class="fa fa-envelope-o fa-fw pull-right"></i>
                                        <span class="badge badge-danger pull-right">5</span> Minhas Solicitações</a>
                                    <a href="#"><i class="fa fa-question fa-fw pull-right"></i>Ajuda</a>
                                </li>

                                <li class="divider"></li>

                                <li>
                                    <a href="#">
                                        <i class="fa fa-user fa-fw pull-right"></i>
                                        Meus dados
                                    </a>
                                    <a data-toggle="modal" href="#modal-user-settings">
                                        <i class="fa fa-cog fa-fw pull-right"></i>
                                        Opções
                                    </a>
                                </li>

                                <li class="divider"></li>

                                <li>
                                    <a href="#"><i class="fa fa-ban fa-fw pull-right"></i>Sair</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <aside class="left-side sidebar-offcanvas">
                <section class="sidebar">
                    <div class="user-panel">
                        <div class="pull-left image">
                            <img src="img/avatarufpr.png" class="img-circle" alt="User Image" />
                        </div>
                        <div class="pull-left info">
                            <p>Olá Evandro!</p>
                            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                        </div>
                    </div>
                    <form action="#" method="get" class="sidebar-form">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="Pesquisar..."/>
                            <span class="input-group-btn">
                                <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </form>
                    <ul class="sidebar-menu">
                        <li>
                            <a href="#" data-toggle="modal" data-target="#novaSolicitacao">
                                <i class="fa fa-envelope-o"></i> <span>Nova Solicitação</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-user"></i> <span>Minhas Solicitações</span>
                            </a>
                        </li>

                    </ul>
                </section>
            </aside>
            <aside class="right-side">
                <section class="content">
                    <div class="row">
                        <div class="col-lg-9">
                            <section class="panel">
                                <header class="panel-heading">
                                    Requerimento para Outras Solicitações
                                </header>
                                <div class="panel-body">
                                    <form class="form-horizontal" role="form">
                                        <div class="form-group">
                                            <label  class="col-lg-2 col-sm-2 control-label">Nome</label>
                                            <div class="col-lg-10">
                                                <input type="text" class="form-control" value="Evandro Morini Silva" disabled>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label  class="col-lg-2 col-sm-2 control-label">Matrícula</label>
                                            <div class="col-lg-10">
                                                <input type="text" class="form-control" value="GRR20121401" disabled>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label  class="col-lg-2 col-sm-2 control-label">Curso</label>
                                            <div class="col-lg-10">
                                                <input type="text" class="form-control" value="TADS - NOITE" disabled>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label  class="col-lg-2 col-sm-2 control-label">Requer</label>
                                            <div class="col-lg-10">
                                                <textarea class="form-control" rows="5" placeholder="Digite aqui sua solicitação..." required></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button type="submit" class="btn btn-info">Enviar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </section>
                        </div>
                    </div>
                </section>
            </aside>
        </div>

        <div id="novaSolicitacao" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Escolha o tipo de Serviço: </h4>
                    </div>
                    <div class="modal-body">
                        <p>Opções...</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
