<script type="text/javascript">
    $(document).ready(function () {
        $("#telinput").inputmask('(99) 9999-9999', { showMaskOnFocus: false, showMaskOnHover: false});
    });
</script>

<div class="col-lg-8">
    <section class="panel">
        <header class="panel-heading text-center">
            Editar Usuário
        </header>
        <div class="panel-body">
            <div class="form-group col-lg-14 text-center">
                <?php echo $this->flashMessenger()->renderCurrent('error', array('alert alert-block alert-danger')); ?>
                <?php echo $this->flashMessenger()->renderCurrent('info', array('alert alert-info')); ?>
                <?php echo $this->flashMessenger()->renderCurrent('success', array('alert alert-success')); ?>
            </div>
            <form name="editarUsuario" class="form-horizontal" role="form" method="post" action="<?php echo $this->url('adm/editar-usuario', array('id' => $this->id)); ?>">
                <div class="form-group">
                    <label  class="col-lg-2 col-sm-2 control-label">CPF </label>
                    <div class="col-lg-8">
                        <input id="cpfinput" class="form-control" type="text" value="<?php echo $this->usuario->getCpf(); ?>" maxlength="11" required="required" placeholder="Insira o CPF" name="cpf" readonly>
                        <input type="hidden" name="id" value="<?php echo $this->id; ?>">
                    </div>
                </div>
                <div class="form-group">
                    <label  class="col-lg-2 col-sm-2 control-label">Nome </label>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" value="<?php echo $this->usuario->getNome(); ?>" maxlength="255" required="required" placeholder="Nome Completo" name="nome">
                    </div>
                </div>

                <?php if ($this->usuario->getFkPerfil() != 1) : ?>
                    <div class="form-group">
                        <label  class="col-lg-2 col-sm-2 control-label">Perfil </label>
                        <div class="col-lg-8">
                            <select class="form-control" required="required" name="perfil">
                                <?php foreach ($this->perfisUsuario as $perfil) : ?>
                                    <?php if ($perfil['id'] != 1) : ?>
                                        <option value="<?php echo $perfil['id']; ?>" <?php if($perfil['id'] == $this->usuario->getFkPerfil()){echo 'selected';} ?>><?php echo $perfil['desc_perfil'] . ' - ' . $perfil['desc_curso']; ?></option>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-8">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="adm" <?php if($this->usuario->getAdm() == 1){ echo 'checked'; } ?>> Administrador
                                </label>
                            </div>
                        </div>
                    </div>
                <?php else: ?>
                    <div class="form-group">
                        <label class="col-lg-2 col-sm-2 control-label">Matrícula</label>
                        <div class="col-lg-8">
                            <input class="form-control" type="text" value="<?php echo $this->matricula; ?>" maxlength="11" required="required" placeholder="GRRXXXXXXXX" name="matricula" readonly>
                        </div>
                    </div>
                    <div class="form-group">
                        <label  class="col-lg-2 col-sm-2 control-label">Curso </label>
                        <div class="col-lg-8">
                            <select class="form-control" required="required" name="curso">
                                <?php foreach ($this->cursosUsuario as $curso) : ?>
                                        <option value="<?php echo $curso->getId(); ?>" <?php if($curso->getId() == $this->idCurso){ echo 'selected'; } ?>><?php echo $curso->getDescricao(); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                <?php endif; ?>

                <div class="form-group">
                    <label  class="col-lg-2 col-sm-2 control-label">Telefone </label>
                    <div class="col-lg-8">
                        <input id="telinput" class="form-control" type="text" value="<?php echo $this->usuario->getTelefone(); ?>" maxlength="15" required="required" placeholder="(DDD)XXXX-XXXX" name="telefone">
                    </div>
                </div>
                <div class="form-group">
                    <label  class="col-lg-2 col-sm-2 control-label">Email </label>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" value="<?php echo $this->usuario->getEmail(); ?>" required="required" placeholder="usuario@dominio.com" name="email">
                    </div>
                </div>
                <div class="form-group">
                    <label  class="col-lg-2 col-sm-2 control-label">Senha </label>
                    <div class="col-lg-8">
                        <input class="form-control" type="password" value="" placeholder="Preencha apenas em caso de troca de senha" name="password">
                    </div>
                </div>
                <div class="form-group">
                    <div class="text-center">
                        <input type="reset" id="resetbutton" class="btn btn-warning" value="Limpar">
                        <input class="btn btn-success" type="submit" value="Salvar Alterações">
                    </div>
                </div>
                <p class="text-center"><a href="<?php echo $this->url('adm');?>">Voltar</a></p>
            </form>
        </div>
    </section>
</div>