<div class="col-lg-12">
    <section class="panel general">
        <header class="panel-heading tab-bg-dark-navy-blue">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a data-toggle="tab" href="#usuarios">Usuários</a>
                </li>
                <li class="">
                    <a data-toggle="tab" href="#cursos">Cursos</a>
                </li>
                <li class="">
                    <a data-toggle="tab" href="#disciplinas">Disciplinas</a>
                </li>
                <li class="">
                    <a data-toggle="tab" href="#professores">Professores</a>
                </li>
            </ul>
        </header>
        <div class="tab-content">
            <div id="usuarios" class="tab-pane active">
                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th>Nome</th>
                            <th>Matrícula</th>
                            <th>Curso</th>
                            <th>Perfil</th>
                            <th></th>
                        </tr>
                        <tr>
                            <td>Evandro Morini Silva</td>
                            <td>GRR20121401</td>
                            <td>Tecnologia em Análise e Desenvolvimento de Sistemas</td>
                            <td>Aluno</td>
                            <td>
                                <a class="btn btn-success" href="#encaminhar" data-toggle="modal"> Visualizar </a>
                                <a class="btn btn-warning" href="#encaminhar" data-toggle="modal"> Editar </a>
                                <a class="btn btn-danger" href="#encaminhar" data-toggle="modal"> Excluir </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div id="cursos" class="tab-pane">
                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th>Código</th>
                            <th>Descrição</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                        <tr>
                            <td>48A</td>
                            <td>Tecnologia em Análise e Desenvolvimento de Sistemas</td>
                            <td>Ativo</td>
                            <td>
                                <a class="btn btn-success" href="#encaminhar" data-toggle="modal"> Visualizar </a>
                                <a class="btn btn-warning" href="#encaminhar" data-toggle="modal"> Editar </a>
                                <a class="btn btn-danger" href="#encaminhar" data-toggle="modal"> Excluir </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div id="disciplinas" class="tab-pane">
                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th>Código</th>
                            <th>Descrição</th>
                            <th>Curso</th>
                            <th>Professor</th>
                            <th></th>
                        </tr>
                        <tr>
                            <td>TI027</td>
                            <td>Prática de Algoritmos</td>
                            <td>Tecnologia em Análise e Desenvolvimento de Sistemas</td>
                            <td>Luiz Antonio Pereira Neves</td>
                            <td>
                                <a class="btn btn-success" href="#encaminhar" data-toggle="modal"> Visualizar </a>
                                <a class="btn btn-warning" href="#encaminhar" data-toggle="modal"> Editar </a>
                                <a class="btn btn-danger" href="#encaminhar" data-toggle="modal"> Excluir </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div id="professores" class="tab-pane">
                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th>Nome</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                        <tr>
                            <td>Luiz Antonio Pereira Neves</td>
                            <td>lapneves@gmail.com</td>
                            <td>Ativo</td>
                            <td>
                                <a class="btn btn-success" href="#encaminhar" data-toggle="modal"> Visualizar </a>
                                <a class="btn btn-warning" href="#encaminhar" data-toggle="modal"> Editar </a>
                                <a class="btn btn-danger" href="#encaminhar" data-toggle="modal"> Excluir </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</div>