<?php
$form->setAttribute('action', $this->url('autenticacao', array('action' => 'index')))
        ->setAttribute('class', 'form-horizontal text-center');
$form->prepare();
?>
<div class="col-lg-6 col-md-offset-3">
    <div class="text-center">
        <img src="<?php echo $this->basePath('img/ufpr-inicio.gif') ?>" alt="">
    </div>
    <section class="panel">
        <header class="panel-heading text-center">
            Bem vindo a secretaria online
        </header>
        <div class="panel-body">
            <?php echo $this->form()->openTag($form); ?>
            <div class="form-group col-lg-14">
                <?php echo $this->flashMessenger()->render('error', array('alert alert-block alert-danger')); ?>
                <?php echo $this->flashMessenger()->render('info', array('alert alert-info')); ?>
                <?php echo $this->flashMessenger()->render('success', array('alert alert-success')); ?>
            </div>
            <div class="form-group">
                <label class="col-lg-2 col-sm-2 control-label"><?php echo $form->get('login')->getLabel(); ?></label>
                <div class="col-lg-10">
                    <?php echo $this->formInput($form->get('login')); ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-2 col-sm-2 control-label"><?php echo $form->get('password')->getLabel(); ?></label>
                <div class="col-lg-10">
                    <?php echo $this->formInput($form->get('password')); ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-8">
                    <p class="help-block">Primeiro acesso? <a href="#">Clique aqui</a></p>
                    <?php echo $this->formRow($form->get('submit')); ?>
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </section>
</div>