<div class="col-lg-6 col-md-offset-3">
    <div class="text-center" style="padding-bottom: 100px;"></div>
    <div class="text-center">
        <img src="<?php echo $this->basePath('img/ufpr-inicio.gif') ?>" alt="">
    </div>
    <section class="panel text-center">
        Seu cadastro está ativo! <a href="<?php  echo $this->url('autenticacao');?>">Clique aqui</a> para efetuar o login.
    </section>
</div>