<?php
$form->setAttribute('action', $this->url('home/editar-usuario'))
        ->setAttribute('class', 'form-horizontal text-center');
$form->prepare();
?>
<div class="col-lg-10">
    <section class="panel">
        <header class="panel-heading text-center">
            Meus dados
        </header>
        <div class="panel-body">
            <?php echo $this->form()->openTag($form); ?>
            <div class="form-group col-lg-14 text-center">
                <?php echo $this->flashMessenger()->render('error', array('alert alert-block alert-danger')); ?>
                <?php echo $this->flashMessenger()->render('info', array('alert alert-info')); ?>
                <?php echo $this->flashMessenger()->render('success', array('alert alert-success')); ?>
            </div>
            <div class="form-group">
                <label class="col-lg-4 col-sm-2 control-label"><?php echo $form->get('cpf')->getLabel(); ?></label>
                <div class="col-lg-6">
                    <?php echo $this->formInput($form->get('cpf')->setValue($this->usuario->getCpf())); ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-4 col-sm-2 control-label"><?php echo $form->get('nome')->getLabel(); ?></label>
                <div class="col-lg-6">
                    <?php echo $this->formInput($form->get('nome')->setValue($this->usuario->getNome())); ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-4 col-sm-2 control-label"><?php echo $form->get('matricula')->getLabel(); ?></label>
                <div class="col-lg-6">
                    <?php echo $this->formInput($form->get('matricula')->setValue($this->matricula)); ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-4 col-sm-2 control-label"><?php echo $form->get('curso')->getLabel(); ?></label>
                <div class="col-lg-6">
                    <?php echo $this->formSelect($form->get('curso')); ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-4 col-sm-2 control-label"><?php echo $form->get('dta_nasc')->getLabel(); ?></label>
                <div class="col-lg-6">
                    <?php echo $this->formInput($form->get('dta_nasc')->setValue($this->usuario->getDtaNasc())); ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-4 col-sm-2 control-label"><?php echo $form->get('email')->getLabel(); ?></label>
                <div class="col-lg-6">
                    <?php echo $this->formInput($form->get('email')->setValue($this->usuario->getEmail())); ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-4 col-sm-2 control-label"><?php echo $form->get('password')->getLabel(); ?></label>
                <div class="col-lg-6">
                    <?php echo $this->formInput($form->get('password')); ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-4 col-sm-2 control-label"><?php echo $form->get('password_repeat')->getLabel(); ?></label>
                <div class="col-lg-6">
                    <?php echo $this->formInput($form->get('password_repeat')); ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-8">
                    <?php echo $this->formRow($form->get('submit')); ?>
                    <input type="reset" id="resetbutton" class="btn btn-warning" value="Limpar">
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </section>
</div>