<div class="col-lg-12">
    <section class="panel">
        <header class="panel-heading text-center">
            <?php 
            setlocale(LC_ALL, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');  
            echo utf8_encode(strftime('%A, %d de %B de %Y', strtotime('today'))); ?>
        </header>
        <div class="panel-body text-justify">
            <div class="col-lg-6">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pulvinar ex non quam sollicitudin, ac vulputate dui iaculis. Mauris nec diam eget urna gravida rutrum ac in risus. Ut porta consequat tristique. Duis accumsan malesuada magna, nec molestie nulla vehicula sit amet. Integer lectus lorem, dapibus a urna id, interdum ornare erat. Suspendisse potenti. In hac habitasse platea dictumst. Nulla ac sem mattis, efficitur dui ac, scelerisque felis. Sed vulputate massa ante, sed volutpat enim tincidunt eget. Proin sollicitudin, quam id volutpat aliquam, metus sapien dapibus arcu, at sollicitudin ipsum lacus vel purus. Mauris varius velit id erat porttitor, sit amet faucibus est iaculis. Proin faucibus mauris at rhoncus aliquam. Aliquam molestie elementum fringilla. Sed a lobortis orci, eget efficitur mi.
            </div>
            <div class="col-lg-6">
                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce vehicula nibh eget turpis porta mollis. In sit amet nisi eget turpis tristique finibus. Curabitur varius nulla in turpis ullamcorper gravida. Vestibulum dignissim elit sem, sed euismod augue pulvinar vel. Nunc hendrerit tempor interdum. In fermentum ultricies tempus. Suspendisse malesuada diam id pellentesque consequat. Vestibulum nec tincidunt urna. Aliquam id dui convallis, gravida arcu in, fermentum magna. Sed nec lacus ut purus gravida mollis. Mauris feugiat nisl pretium urna tincidunt, hendrerit tincidunt ligula iaculis. Vivamus ullamcorper quam at enim lobortis condimentum. Duis nec nibh fringilla leo facilisis blandit. Praesent sollicitudin, elit nec euismod congue, dui nulla porttitor lorem, quis accumsan nulla ligula luctus dui.
            </div>
        </div>
    </section>
</div>