<?php
$form->setAttribute('action', $this->url('home/reset-senha'))
        ->setAttribute('class', 'form-horizontal text-center');
$form->prepare();
?>
<div class="col-lg-6 col-md-offset-3">
    <div class="text-center" style="padding-bottom: 80px;"></div>
    <section class="panel">
        <header class="panel-heading text-center">
            Esqueci minha senha
        </header>
        <div class="panel-body">
            <?php echo $this->form()->openTag($form); ?>
            <div class="form-group col-lg-14">
                <?php echo $this->flashMessenger()->renderCurrent('error', array('alert alert-block alert-danger')); ?>
                <?php echo $this->flashMessenger()->renderCurrent('info', array('alert alert-info')); ?>
                <?php echo $this->flashMessenger()->renderCurrent('success', array('alert alert-success')); ?>
            </div>
            <div class="form-group">
                <label class="col-lg-2 col-sm-2 control-label"><?php echo $form->get('email')->getLabel(); ?></label>
                <div class="col-lg-10">
                    <?php echo $this->formInput($form->get('email')); ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-2 col-sm-2 control-label"><?php echo $form->get('password')->getLabel(); ?></label>
                <div class="col-lg-10">
                    <?php echo $this->formInput($form->get('password')); ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-2 col-sm-2 control-label"><?php echo $form->get('password_repeat')->getLabel(); ?></label>
                <div class="col-lg-10">
                    <?php echo $this->formInput($form->get('password_repeat')); ?>
                </div>
                <p class="help-block">***A senha deve conter ao menos 8 dígitos***</p>
            </div>
            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-8">
                    <?php echo $this->formRow($form->get('submit')); ?>
                    <input type="reset" id="resetbutton" class="btn btn-warning" value="Limpar">
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
        <p class="text-center"><a href="<?php echo $this->url('autenticacao');?>">Voltar</a></p>
        <br>
    </section>
</div>