<div class="col-lg-6 col-md-offset-3">
    <div class="text-center" style="padding-bottom: 80px;"></div>
    <section class="panel">
        <header class="panel-heading text-center">
            Esqueci minha senha
        </header>
        <div class="panel-body">
            <form id="reset-senha" class="form-horizontal text-center" action="<?php echo $this->url('home/reset-senha'); ?>" name="reset-senha" method="POST">
                <div class="form-group col-lg-14">
                    <?php echo $this->flashMessenger()->renderCurrent('error', array('alert alert-block alert-danger')); ?>
                    <?php echo $this->flashMessenger()->renderCurrent('info', array('alert alert-info')); ?>
                    <?php echo $this->flashMessenger()->renderCurrent('success', array('alert alert-success')); ?>
                </div>
                <p class="text-center">Informe o email utilizado em seu cadastro para dar continuidade ao processo de reset de senha.</p>
                <div class="form-group">
                    <label class="col-lg-2 col-sm-2 control-label">Email</label>
                    <div class="col-lg-10">
                        <input class="form-control" type="text" value="" required="required" placeholder="usuario@dominio.com" name="email">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-8">
                        <input id="submitbutton" class="btn btn-info" type="submit" value="Enviar" name="submit">
                        <input id="resetbutton" class="btn btn-warning" type="reset" value="Limpar">
                    </div>
                </div>

            </form>
        </div>
        <p class="text-center"><a href="<?php echo $this->url('autenticacao'); ?>">Voltar</a></p>
        <br>
    </section>
</div>