<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Secretaria Online</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <link href="<?php echo $this->basePath('css/bootstrap.min.css');?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('css/font-awesome.min.css');?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('css/ionicons.min.css');?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('css/style.css');?>" rel="stylesheet" type="text/css" />
        <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
        <script src="<?php echo $this->basePath('js/jquery.min.js');?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('js/bootstrap.min.js');?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('js/Director/app.js');?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('js/plugins/input-mask/jquery.inputmask.js');?>"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $(function () {
                    $("#dateinput").inputmask("99/99/9999");
            });
        });
        </script>
    </head>
    <body class="skin-black">
        <header class="header">
            <a href="#" class="logo">Secretaria Online</a>
            <nav class="navbar navbar-static-top" role="navigation">
                <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-right">
                    <ul class="nav navbar-nav">
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-user"></i>
                                <span><?php echo $this->nome_usuario_layout; ?> <i class="caret"></i></span>
                            </a>
                            <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
                                <li class="dropdown-header text-center">OPÇÕES</li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-envelope-o fa-fw pull-right"></i>
                                        <!--<span class="badge badge-danger pull-right">5</span> -->
                                        Minhas Solicitações</a>
                                </li>

                                <li class="divider"></li>

                                <li>
                                    <a href="#">
                                        <i class="fa fa-user fa-fw pull-right"></i>
                                        Meus dados
                                    </a>
                                </li>

                                <li class="divider"></li>

                                <li>
                                    <a href="<?php  echo $this->url('logout');?>">
                                    <i class="fa fa-ban fa-fw pull-right"></i>Sair</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <aside class="left-side sidebar-offcanvas">
                <section class="sidebar">
                    <div class="user-panel">
                        <div class="pull-left image">
                            <img src="img/avatarufpr.png" class="img-circle" alt="User Image" />
                        </div>
                        <div class="pull-left info">
                            <p> 
                                <?php
                                    $firstname = explode(" ", $this->nome_usuario_layout);
                                    echo 'Olá ' . $firstname[0] . '!';
                                ?>
                            </p>
                            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                        </div>
                    </div>
                    <form action="#" method="get" class="sidebar-form">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="Pesquisar..."/>
                            <span class="input-group-btn">
                                <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </form>
                    <ul class="sidebar-menu">
                        <li>
                            <a href="#" data-toggle="modal" data-target="#novaSolicitacao">
                                <i class="fa fa-envelope-o"></i> <span>Nova Solicitação</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-user"></i> <span>Minhas Solicitações</span>
                            </a>
                        </li>

                    </ul>
                </section>
            </aside>
            <aside class="right-side">
                <section class="content">
                    <div class="row">
                        <?php echo $this->content; ?>
                    </div>
                </section>
            </aside>
        </div>
        <!-- Modais -->
        <div id="novaSolicitacao" class="modal fade" role="dialog">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
              </div>
              <div class="modal-body">
                <p>Some text in the modal.</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
        
    </body>
</html>
