<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Secretaria Online</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <link href="<?php echo $this->basePath('css/bootstrap.min.css');?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('css/font-awesome.min.css');?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('css/ionicons.min.css');?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('css/style.css');?>" rel="stylesheet" type="text/css" />
        <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
        <script src="<?php echo $this->basePath('js/jquery.min.js');?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('js/bootstrap.min.js');?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('js/Director/app.js');?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('js/plugins/input-mask/jquery.inputmask.js');?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('js/secretaria/secretaria.js');?>" type="text/javascript"></script>
    </head>
    <body class="skin-black">
        <section class="content">
            <?php echo $this->content; ?>
        </section>
    </body>
</html>
